remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
title: Gonçalo Carvalho`s Posts
description: Random posts about security, kernel exploitation, and other stuff
show_downloads: false
markdown: kramdown
